server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/administration?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: lxy3.1415926353
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  data:
    redis:
      host: localhost
      port: 6379
#Mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5t6ZL8rrrNAwTGSryYdh
    accessKeySecret: bGkmhLrNlKvZ2q8Yf0DjUoDUzFeUpN
    bucketName: web-tail01
# spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug;
